### ISSUE TITLE
reportData.coverage.project.file is not iterable

### ISSUE THREAD

**Issue by eloisetaylor5693** [saschanowak/CloverCodeCoverageSummary#42]
When using this github action I get the error: 
`Error: reportData.coverage.project.file is not iterable` 

## My setup
`"jest": "^27.0.0",`

To generate the clover coverage report I'm running: `jest --ci --coverage` which generates the folder in the root of my project
![image](https://github.com/saschanowak/CloverCodeCoverageSummary/assets/20887184/e8f97a78-aec3-48ae-bd72-b5940bcbb1f9)

The workflow file:
```yaml
permissions:
  checks: write
  contents: read
  packages: read
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: node-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile --check-files
      - run: yarn test:ci
      - name: Clover Code Coverage Summary
        uses: saschanowak/CloverCodeCoverageSummary@0.3.1
        with:
          filename: ./coverage/clover.xml
      - name: 'Add Code Coverage to Job Summary'
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY
```
